name: Scrape Mike Ball Expeditions

on:
  push:
    branches: [ main ]
    paths:
      - scripts/scrape.py
      - requirements.txt
      - .github/workflows/scrape.yml
  schedule:
    - cron: "0 0 * * *"   # daily at 00:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    concurrency:
      group: mikeball-feed
      cancel-in-progress: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Python deps
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python scripts/scrape.py

      - name: Commit updated JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Auto-update availability feed" || echo "No changes to commit"
          git pull --rebase origin main || true
          git push origin HEAD:main
          
