name: Scrape Mike Ball Expeditions

on:
  push:
    branches: [ main ]
    paths:
      - scripts/scrape.py
      - requirements.txt
      - .github/workflows/scrape.yml
  schedule:
    - cron: "0 0 * * *"   # run every day at 00:00 UTC
  workflow_dispatch:       # allow manual run from GitHub UI

permissions:
  contents: write          # allow the workflow to commit/push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python scripts/scrape.py

      - name: Commit updated JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add mikeball.json
          git commit -m "Auto-update mikeball.json" || echo "No changes to commit"
          git push
